# Generated by Django 2.0.5 on 2018-05-11 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название опции')),
                ('value', models.CharField(editable=False, max_length=200, verbose_name='Значение опции')),
                ('cost', models.PositiveIntegerField(default=0, help_text='указывается в рублях', verbose_name='Стоимость опции')),
            ],
            options={
                'verbose_name': 'Значение для подсчета',
                'verbose_name_plural': 'Значения для подсчета',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='FieldEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='Заголовок поля')),
                ('name', models.CharField(editable=False, max_length=200, verbose_name='Название поля')),
            ],
            options={
                'verbose_name': 'Поле опросника',
                'verbose_name_plural': 'Поля опросника',
                'ordering': ('label',),
            },
        ),
        migrations.CreateModel(
            name='FormEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название формы')),
                ('class_name', models.CharField(editable=False, max_length=200, unique=True, verbose_name='Название класса формы')),
            ],
            options={
                'verbose_name': 'Форма опросника',
                'verbose_name_plural': 'Формы опросника',
                'ordering': ('title',),
            },
        ),
        migrations.AddField(
            model_name='fieldentity',
            name='form_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inquirers.FormEntity', verbose_name='Форма опросника'),
        ),
        migrations.AddField(
            model_name='choicescore',
            name='field_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inquirers.FieldEntity', verbose_name='Поле опросника'),
        ),
        migrations.AlterUniqueTogether(
            name='fieldentity',
            unique_together={('form_entity', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='choicescore',
            unique_together={('field_entity', 'value')},
        ),
    ]
